sulu_redirect.redirect_route:
    type: rest
    name_prefix: sulu_redirect.
    resource: sulu_redirect.redirect_route_controller
    options:
        expose: true

sulu_redirect.post_redirect-route_trigger:
    path: /redirect-routes/{id}.{_format}
    methods: POST
    defaults:
        _controller: sulu_redirect.redirect_route_controller::postTriggerAction
        _format: json
