name: Test application
on:
    pull_request: null
    push:
        branches:
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'
jobs:
    php:
        name: 'PHP ${{ matrix.php-version }} (${{ matrix.database }}, ${{ matrix.dependency-versions }})'
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '8.2'
                      database: 'mysql-57'
                      dependency-versions: 'lowest'
                      php-extensions: 'mysql, imagick'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: 'mysql://root:ChangeMe@127.0.0.1:3306/sulu_redirect_test?serverVersion=5.7'

                    - php-version: '8.2'
                      database: 'mysql-57'
                      dependency-versions: 'highest'
                      php-extensions: 'mysql, imagick'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: 'mysql://root:ChangeMe@127.0.0.1:3306/sulu_redirect_test?serverVersion=5.7'

                    - php-version: '8.3'
                      database: 'mysql-57'
                      dependency-versions: 'highest'
                      php-extensions: 'mysql, imagick'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: 'mysql://root:ChangeMe@127.0.0.1:3306/sulu_redirect_test?serverVersion=5.7'

                    - php-version: '8.3'
                      database: 'postgres-14'
                      dependency-versions: 'highest'
                      php-extensions: 'pgsql, imagick'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: 'postgres://symfony:ChangeMe@127.0.0.1:5432/sulu_redirect_test?serverVersion=14'
                          DATABASE_CHARSET: UTF8
                          DATABASE_COLLATE:

                    - php-version: '8.4'
                      database: 'mysql-80'
                      dependency-versions: 'highest'
                      php-extensions: 'mysql, imagick'
                      tools: 'composer:v2'
                      composer-options: '--ignore-platform-reqs'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: 'mysql://root:ChangeMe@127.0.0.1:3306/sulu_redirect_test?serverVersion=8.0'

                    - php-version: '8.5'
                      database: 'mysql-84'
                      dependency-versions: 'highest'
                      php-extensions: 'mysql, imagick'
                      tools: 'composer:v2'
                      composer-options: '--ignore-platform-reqs'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: 'mysql://root:ChangeMe@127.0.0.1:3306/sulu_redirect_test?serverVersion=8.4'

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Start Database
              run: docker compose -f Tests/docker/docker-compose.${{ matrix.database }}.yml up --wait

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php-version }}'
                  extensions: '${{ matrix.php-extensions }}'
                  tools: '${{ matrix.tools }}'
                  coverage: none

            - name: Remove Lint Tools
              # These tools are not required to run tests, so we are removing them to improve dependency resolving and
              # testing lowest versions.
              run: composer remove "*php-cs-fixer*" "*phpstan*" "*rector*" --dev --no-update

            - name: Install composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{matrix.dependency-versions}}
                  composer-options: ${{matrix.composer-options}}

            - name: Bootstrap test environment
              run: composer bootstrap-test-environment
              env: '${{ matrix.env }}'

            - name: Execute test cases
              run: time composer test
              env: '${{ matrix.env }}'

    php-lint:
        name: 'PHP Lint'
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: 'mysql://root:root@127.0.0.1/sulu_redirect_test?serverVersion=5.7'

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: 'mysql, imagick'
                  tools: 'composer:v2'
                  coverage: none

            - name: Install composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: highest

            - name: Lint code
              run: composer lint
